apiVersion: v1
kind: ConfigMap
metadata:
  name: veo-demo-config
  namespace: veo-demo
data:
  COMFYUI_BASE_URL: "http://comfyui-service.comfyui.svc.cluster.local:8188"
  GOOGLE_CLIENT_ID: ""
  ALLOWED_AUTH_DOMAIN: ""
  VEO_ASSETS_BUCKET: "veo-media"
